// Code generated by protoc-gen-go.
// source: msg/apps.proto
// DO NOT EDIT!

/*
Package apps is a generated protocol buffer package.

It is generated from these files:
	msg/apps.proto

It has these top-level messages:
	UserApps
*/
package apps

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type UserApps struct {
	Apps             []uint32 `protobuf:"varint,1,rep,name=apps" json:"apps,omitempty"`
	Lat              *float64 `protobuf:"fixed64,2,opt,name=lat" json:"lat,omitempty"`
	Lon              *float64 `protobuf:"fixed64,3,opt,name=lon" json:"lon,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserApps) Reset()         { *m = UserApps{} }
func (m *UserApps) String() string { return proto.CompactTextString(m) }
func (*UserApps) ProtoMessage()    {}

func (m *UserApps) GetApps() []uint32 {
	if m != nil {
		return m.Apps
	}
	return nil
}

func (m *UserApps) GetLat() float64 {
	if m != nil && m.Lat != nil {
		return *m.Lat
	}
	return 0
}

func (m *UserApps) GetLon() float64 {
	if m != nil && m.Lon != nil {
		return *m.Lon
	}
	return 0
}

func init() {
}
